description: Execution environment with ./target/release/gen-orb-mcp pre-installed.
docker:
- image: jerusdp/./target/release/gen-orb-mcp:<< parameters.tag >>
parameters:
  tag:
    type: string
    description: Docker image tag.
    default: latest
