description: Run build command in a dedicated job.
executor: default
parameters:
  input:
    type: string
    description: Directory containing generated MCP server source
steps:
- checkout
- build:
    input: << parameters.input >>
